version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8081:8080'
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8080 || exit 1']
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3
